### ISSUE TITLE
Bug - clear components

### ISSUE THREAD

**Issue by librasteve** [FCO/Cromponent#5]
There's a sneaky bug that only shows when Cromponent reused in multiple routes ... I have added a patch - `clear_components` to this PR to help avoid that making it through to released code.

Caused by `my %components;` lexical getting reused in different routes.

Longer term is that this needs to be factored out ... which I will do now in my working copy...

**Comment by FCO** [comment]
Could you confirm me if this continues on the new version? If it does, would you mind to share a piece of code to reproduce that, please?

**Comment by librasteve** [comment]
Let me elaborate the problem, since i think it is quite easy to explain.

The current Cromponent code goes something like:

```
unit class Cromponent.rakumod;
my %cromponents;

sub xyx is export {}
```

and 

cromponent.raku
```
route {
  add-component X;
  get -> { template-with-components ... X ... }
}

my $Cro::Service...
$http.start;
```

---

My usage (which is a common model, I think) however is like this:

Routes.rakumod
```
      use Cro::Website::Basic::Routes::SHARC;
      include sharc => sharc-routes;

       use Cro::Website::Basic::Routes::Happy-TM-Xmas;
      include happy_tm_xmas => happy_tm_xmas-routes;
```

Then I have:

SHARC.rakumod
```
sub sharc-routes() is export {

    route {
        add-components MyTable, Row, Cell, Grid, Item;

        get -> {
            template-with-components $template, $topic;
        }
    }
```

Happy-TM-Xmas.rakumod
```
sub happy_tm_xmas-routes() is export {

    route {

        add-components Results, ActiveTable, THead, HCell, Row, Cell;

        get -> {
            template-with-components $index, $topic;
        }
...
}
```

As the user clicks around the two included route blocks, so add-components is called alternately with two different sets of Cromponents... which all get appended to the `my %components` lexical hash.

This is what I mean when I say that the current code is "not reentrant".

My initial patch was to have a `clear-components` sub that would go `%components := {}` when needed, but that ends up with a lot of loading and unloading since it (and the subsequent add) has to be called in the get / post block (otherwise the components added when the last route block is used will win.)

Therefore, I thought it would be best - at the scale of "include route block" to make `class Cromponent {}` a true class with attr `has %.components` and to have each route block include take it's own instance and to maintain it component list state.

The _cost_ is that the instance has to be passed to the `template-with-components` sub (guess we could make that a method).

This is my current working code - you can see it here (on branch 02-sharc1):
https://github.com/librasteve/raku-Cro-Website-Basic/blob/02-sharc1/lib/Cromponent.rakumod
and is used via
https://github.com/librasteve/raku-Cro-Website-Basic/blob/02-sharc1/lib/Cro-Website-Basic/Routes/SHARC.rakumod

(The other change on the caller side is the use of the $topic var - that is only need in the functional case and did not require any change in the Cromponent.rakumod code)

**Comment by librasteve** [comment]
oh and I have more recently added a `location` attribute to the class (in branch `03-sharc2`) so that the `url-part` generated routes work correctly when route blocks are included

for more extensive website projects, this allows the use of multiple concurrent Cromponent libraries
